### ISSUE TITLE
Tailscale function in this setup?

### ISSUE THREAD

**Issue by bobsummerwill** [odyslam/darkfi-starter#4]
(If there is a better place for this discussion, I am happy to move elsewhere)

Thanks for creating this very useful project!

Please excuse my ignorance, but what function is Tailscale performing?  Wouldn't the IRC client and ircd process usually be on the same device?   What privacy benefit does routing that through Tailscale provide?   I assume there is a benefit here which I am missing.

Best wishes!

**Comment by odyslam** [comment]
Hey, thank you for this issue (just saw it -- not sure how I missed it).

The benefit is that I run this setup at a raspberry-pi at home, but want to access ircd and taud from anywhere when working remotely, as also from my phone. 

I added a docker-compose file that doesn't include tailscale for people that don't need the extra networking help

**Comment by bobsummerwill** [comment]
Aha.  That makes sense.

Thanks for the additional context, @odyslam.
